CREATE TABLE CATEGORIA (
  cod_categoria INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  descricao VARCHAR(45) NULL,
  resumo LONGTEXT NULL,
  PRIMARY KEY(cod_categoria)
);

CREATE TABLE CLIENTE (
  cod_cliente INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ENDERECO_cod_cliente INTEGER UNSIGNED NOT NULL,
  nome VARCHAR(50) NULL,
  PRIMARY KEY(cod_cliente),
  INDEX CLIENTE_FKIndex1(ENDERECO_cod_cliente)
);

CREATE TABLE EMPREGADO (
  cod_empregado INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  EMPREGADO_cod_empregado INTEGER UNSIGNED NOT NULL,
  nome VARCHAR(45) NULL,
  cod_chefe INTEGER UNSIGNED NULL,
  PRIMARY KEY(cod_empregado),
  INDEX EMPREGADO_FKIndex1(EMPREGADO_cod_empregado)
);

CREATE TABLE ENDERECO (
  cod_cliente INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  rua VARCHAR(50) NULL,
  cidade VARCHAR(50) NULL,
  PRIMARY KEY(cod_cliente)
);

CREATE TABLE ITEM (
  cod_pedido INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PEDIDO_cod_pedido INTEGER UNSIGNED NOT NULL,
  PRODUTO_cod_produto INTEGER UNSIGNED NOT NULL,
  cod_produto INTEGER UNSIGNED NULL,
  PRIMARY KEY(cod_pedido),
  INDEX ITEM_FKIndex1(PRODUTO_cod_produto),
  INDEX ITEM_FKIndex2(PEDIDO_cod_pedido)
);

CREATE TABLE PEDIDO (
  cod_pedido INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CLIENTE_cod_cliente INTEGER UNSIGNED NOT NULL,
  EMPREGADO_cod_empregado INTEGER UNSIGNED NOT NULL,
  data_pedido DATE NULL,
  hora_pedido TIME NULL,
  observacao VARCHAR(100) NULL,
  cod_cliente INTEGER UNSIGNED NULL,
  cod_empregado INTEGER UNSIGNED NULL,
  PRIMARY KEY(cod_pedido),
  INDEX PEDIDO_FKIndex1(EMPREGADO_cod_empregado),
  INDEX PEDIDO_FKIndex2(CLIENTE_cod_cliente)
);

CREATE TABLE PRODUTO (
  cod_produto INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CATEGORIA_cod_categoria INTEGER UNSIGNED NOT NULL,
  descricao VARCHAR(45) NULL,
  preco DECIMAL(7,2) NULL,
  cod_categoria INTEGER UNSIGNED NULL,
  PRIMARY KEY(cod_produto),
  INDEX PRODUTO_FKIndex1(CATEGORIA_cod_categoria)
);


